-- MyGigs — extra DJ-stijlen (idempotent op slug; bestaande blijven ongemoeid).
insert into genres (name, slug)
select v.name, v.slug
from (values
  ('Deep house', 'deep-house'),
  ('Tech house', 'tech-house'),
  ('Progressive house', 'progressive-house'),
  ('Melodic techno', 'melodic-techno'),
  ('Afro house', 'afro-house'),
  ('Jackin house', 'jackin-house'),
  ('Minimal', 'minimal'),
  ('Hard techno', 'hard-techno'),
  ('Trance', 'trance'),
  ('Psytrance', 'psytrance'),
  ('Hardstyle', 'hardstyle'),
  ('Hardcore', 'hardcore'),
  ('EDM', 'edm'),
  ('Electro', 'electro'),
  ('Future bass', 'future-bass'),
  ('Dubstep', 'dubstep'),
  ('Bass', 'bass'),
  ('UK garage', 'uk-garage'),
  ('Grime', 'grime'),
  ('Breakbeat', 'breakbeat'),
  ('Jungle', 'jungle'),
  ('Afrobeats', 'afrobeats'),
  ('Dancehall', 'dancehall'),
  ('Reggaeton', 'reggaeton'),
  ('Moombahton', 'moombahton'),
  ('Baile funk', 'baile-funk'),
  ('R&B', 'rnb'),
  ('Trap', 'trap'),
  ('Drill', 'drill'),
  ('Nu-disco', 'nu-disco'),
  ('Funk', 'funk'),
  ('Soul', 'soul'),
  ('Pop', 'pop'),
  ('Top 40', 'top-40'),
  ('Commercial / Charts', 'commercial'),
  ('90s & 00s', '90s-00s'),
  ('Golden oldies', 'golden-oldies'),
  ('Nederlandstalig', 'nederlandstalig'),
  ('Feest / Après-ski', 'feest-apres-ski'),
  ('Salsa', 'salsa'),
  ('Bachata', 'bachata'),
  ('Kizomba', 'kizomba'),
  ('Zouk', 'zouk'),
  ('Reggae', 'reggae'),
  ('Ambient / Lounge', 'ambient-lounge')
) as v(name, slug)
where not exists (select 1 from genres g where g.slug = v.slug);
